
export const projects = [
  {
    slug: 'portfolio-pulse',
    title: 'Portfolio Pulse',
    description: 'An internal MIS system for Global IME Capital, processing Excel data into interactive dashboards for real-time portfolio analysis.',
    image: { src: '/images/portfolio-pulse.png', hint: 'data analytics dashboard' },
    status: 'Successfully Deployed',
    longDescription: 'Portfolio Pulse is an internal MIS system I built end-to-end for Global IME Capital Limited. It processes raw Excel portfolio data in-browser, generating interactive dashboards for real-time performance, allocation, and gain/loss analysis. This replaced a manual process, bringing unprecedented clarity and speed to executive portfolio supervision.',
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'ShadCN UI', 'Recharts'],
    features: ['In-browser Excel processing', 'Interactive data dashboards', 'Real-time performance metrics', 'Automated reporting'],
    liveLink: null,
    githubLink: null,
  },
  {
    slug: 'meroshare-automation',
    title: 'MeroShare Automation',
    description: "Automated MeroShare's operations like IPO applications, eDIS completions, and verification workflows to enhance efficiency.",
    image: { src: '/images/meroshare-automation.png', hint: 'automation robot' },
    status: 'Personal Project',
    longDescription: "A suite of automation scripts designed to streamline tedious and repetitive tasks on the MeroShare platform, which is central to the Nepalese stock market. These scripts handle applying for IPOs, completing eDIS (Electronic Delivery Instruction Slip), and creating verification workflows for these critical processes. The project significantly reduces manual effort and minimizes the potential for human error.",
    technologies: ['Python', 'Selenium', 'Automation Scripts'],
    features: ['Automated IPO application', 'Automated eDIS completion', 'Custom verification workflows', 'Error handling and logging'],
    liveLink: null,
    githubLink: 'https://github.com/PrameshLuitel/MeroShare-Automation',
  },
  {
    slug: 'automated-form-fillers',
    title: 'Auto Form Filler App for PMS',
    description: 'A utility script that automates filling Portfolio Management Services (PMS) forms, saving time and reducing data entry errors.',
    image: { src: '/images/auto-form-filler.png', hint: 'digital form' },
    status: 'Utility Script',
    longDescription: 'Developed a custom script to automate the tedious process of filling out Portfolio Management Services (PMS) forms for merchant banking clients. By mapping spreadsheet data to form fields, this utility significantly reduces manual data entry time and minimizes errors, ensuring accuracy and efficiency in the client onboarding process.',
    technologies: ['Python', 'Pandas', 'OpenPyXL'],
    features: ['Automated form population', 'Data mapping from Excel', 'Error reduction', 'Batch processing'],
    liveLink: null,
    githubLink: null,
  },
  {
    slug: 'project-vestara',
    title: 'Project Vestara',
    description: 'My flagship venture, a proprietary AI platform designed to become the central nervous system for modern investment firms.',
    image: { src: '/images/project-vestara.png', hint: 'ai brain' },
    status: 'In Development',
    longDescription: "Project Vestara is my flagship venture, a proprietary AI platform designed to become the central nervous system for modern investment firms. It moves beyond simple data retrieval to provide actionable, forward-looking strategic intelligence by transforming market noise into a clear signal of alpha. The vision is to make Vestara an indispensable conversational AI partner for institutional investors.",
    technologies: ['AI/ML', 'LLM', 'Python', 'Next.js', 'Genkit'],
    features: ['Conversational AI Interface', 'Predictive Analytics', 'Regulatory Q&A', 'Portfolio Optimization Simulation'],
    liveLink: null,
    githubLink: null,
  },
];
