
export const projects = [
  {
    slug: 'portfolio-pulse',
    title: 'Portfolio Pulse',
    description: 'An internal MIS system for Global IME Capital, processing Excel data into interactive dashboards for real-time portfolio analysis.',
    longDescription: 'Portfolio Pulse is an internal MIS system I built end-to-end for Global IME Capital Limited. It processes raw Excel portfolio data in-browser, generating interactive dashboards for real-time performance, allocation, and gain/loss analysis. This replaced a manual process, bringing unprecedented clarity and speed to executive portfolio supervision.',
    image: { src: '/images/portfolio-pulse.png', hint: 'data analytics dashboard' },
    status: 'Successfully Deployed',
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'ShadCN UI', 'Recharts'],
    features: ['In-browser Excel processing', 'Interactive data dashboards', 'Real-time performance metrics', 'Automated reporting'],
    liveLink: null,
    githubLink: null,
  },
  {
    slug: 'meroshare-automation',
    title: 'MeroShare Automation',
    description: "Automated MeroShare's operations like IPO applications, eDIS completions, and verification workflows to enhance efficiency.",
    longDescription: "A suite of automation scripts designed to streamline tedious and repetitive tasks on the MeroShare platform, which is central to the Nepalese stock market. These scripts handle applying for IPOs, completing eDIS (Electronic Delivery Instruction Slip), and creating verification workflows for these critical processes. The project significantly reduces manual effort and minimizes the potential for human error.",
    image: { src: '/images/meroshare-automation.png', hint: 'automation robot' },
    status: 'Personal Project',
    technologies: ['Python', 'Selenium', 'Automation Scripts'],
    features: ['Automated IPO application', 'Automated eDIS completion', 'Custom verification workflows', 'Error handling and logging'],
    liveLink: null,
    githubLink: 'https://github.com/PrameshLuitel/MeroShare-Automation',
  },
  {
    slug: 'auto-form-filler-pms',
    title: 'Auto Form Filler App for PMS',
    description: 'A utility script that automates filling Portfolio Management Services (PMS) forms, saving time and reducing data entry errors.',
    longDescription: 'Developed a custom script to automate the tedious process of filling out Portfolio Management Services (PMS) forms for merchant banking clients. By mapping spreadsheet data to form fields, this utility significantly reduces manual data entry time and minimizes errors, ensuring accuracy and efficiency in the client onboarding process.',
    image: { src: '/images/Form_bot.png', hint: 'digital form' },
    status: 'Utility Script',
    technologies: ['Python', 'Pandas', 'OpenPyXL'],
    features: ['Automated form population', 'Data mapping from Excel', 'Error reduction', 'Batch processing'],
    liveLink: null,
    githubLink: null,
  },
  {
    slug: 'project-vestara',
    title: 'Project Vestara',
    description: 'My flagship venture, a proprietary AI platform designed to become the central nervous system for modern investment firms.',
    longDescription: "Project Vestara is my flagship venture, a proprietary AI platform designed to become the central nervous system for modern investment firms. It moves beyond simple data retrieval to provide actionable, forward-looking strategic intelligence by transforming market noise into a clear signal of alpha. The vision is to make Vestara an indispensable conversational AI partner for institutional investors.",
    image: { src: '/images/vestara-logo.png', hint: 'ai brain' },
    status: 'In Development',
    technologies: ['AI/ML', 'LLM', 'Python', 'Next.js', 'Genkit'],
    features: ['Conversational AI Interface', 'Predictive Analytics', 'Regulatory Q&A', 'Portfolio Optimization Simulation'],
    liveLink: null,
    githubLink: null,
  },
  {
    slug: 'nepse-trading-bot',
    title: 'Nepse Trading Bot',
    description: 'A bot that takes client code and client\'s name from an excel sheet and put a buy or sell  order in the right price range whichever has been kept in the excel sheet automating the wrokflow of the traind department in the Portfolio management services.',
    longDescription: "A bot that takes client code and client's name from an excel sheet and put a buy or sell order in the right price range whichever has been kept in the excel sheet automating the wrokflow of the traind department in the Portfolio management services.",
    image: { src: 'https://placehold.co/400x300', hint: 'trading bot' },
    status: 'Utility Script',
    technologies: ['Python', 'Automation', 'Pandas', 'Selenium'],
    features: ['Automated order placement', 'Reads from Excel', 'Price range validation', 'Workflow automation'],
    liveLink: null,
    githubLink: '#',
  },
];

export const researchPapers = [
  {
    title: 'Sentiment-Enhanced Stock Price Prediction in Nepalese Small-Cap Equities Using Natural Language Processing',
    publication: 'Under Peer Review (Journal of Himalaya College of Engineering)',
    link: '#',
    tags: ['NLP', 'Sentiment Analysis', 'NEPSE', 'Small-Cap Equities', 'Peer-Reviewed'],
    summary: 'Developed a hybrid model combining NLP and quantitative market indicators to predict price movements in illiquid, small-cap stocks. This research pioneered NLP-driven financial analysis in the Nepalese capital market by converting qualitative sentiment data into structured features, demonstrating superior performance over traditional models in low-volume environments.',
    isPublished: false,
  },
  {
    title: 'Market Oscillations and Predictive Analytics: AI-Driven Insights into Nepalese Stock Market’s Indices and its Sub-Indices',
    publication: "Published on SSRN | Top Downloads in Emerging & Asian Markets",
    link: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5030130',
    tags: ['Predictive Analytics', 'LSTM', 'Time-Series Forecasting', 'NEPSE', 'SSRN'],
    summary: "Conducted an in-depth analysis of the NEPSE index using LSTM networks and advanced technical indicators. This work engineered a robust forecasting framework, highlighting the applicability of deep learning in structurally inefficient markets where traditional financial models often underperform.",
    isPublished: true,
  },
];
